pipeline:
  name: inputRemote
  identifier: inputRemote
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: stageVar1
            type: String
            default: pra
            description: ""
            required: false
            value: <+input>.default(pra).allowedValues(pra,sha,nt)
        strategy: <+input>
  variables:
    - name: var1
      type: String
      description: ""
      required: false
      value: <+input>.allowedValues(abc,def,ghi)
