pipeline:
  name: p1_remote
  identifier: p1_remote
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  template:
                    templateRef: Approval_Stage
                    versionLabel: v1
        tags: {}
