pipeline:
  name: p1_remote
  identifier: p1_remote
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: app_stage
          versionLabel: v1
