pipeline:
  name: parent_remote
  identifier: parent_remote
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: no default branch
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - user2
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: p3_remote
          project: proj1
          inputs:
            identifier: p3_remote
            stages:
              - stage:
                  identifier: s1
                  type: Approval
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ap1
                            type: HarnessApproval
                            spec:
                              approvers:
                                userGroups: <+input>
          outputs: []
    - stage:
        name: s3
        identifier: s3
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: p2_remote
          project: proj1
          inputs:
            identifier: p2_remote
            stages:
              - stage:
                  identifier: s1
                  type: Approval
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ap1
                            type: HarnessApproval
                            spec:
                              approvers:
                                userGroups: <+input>
          outputs: []
