pipeline:
  name: remote_p1
  identifier: remote_p1
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: t1
          versionLabel: v1
