pipeline:
  name: remote_pip
  identifier: remote_pip
  projectIdentifier: vivek
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: s1
          versionLabel: v1
          gitBranch: b2
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ap1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
