pipeline:
  name: triggerTestPipelineChild
  identifier: triggerTestPipelineChild
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsf
        identifier: dsfvsdfvdsv_as_1_2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    shell: Sh
                    command: <+input>
                  description: <+input>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: <+input>
              namespace: <+input>
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: vivek_conn
        build: <+input>
