pipeline:
  name: triggerParent
  identifier: triggerParent
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: d
        identifier: d
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: triggerTestPipelineChild
          project: naidusanity
          inputs:
            identifier: triggerTestPipelineChild
            stages:
              - stage:
                  identifier: dsf
                  type: CI
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: Run_1
                            type: Run
                            spec:
                              connectorRef: <+input>
                              image: <+input>
                              command: <+input>
                            description: <+input>
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: <+input>
                        namespace: <+input>
            properties:
              ci:
                codebase:
                  build: <+input>
  variables:
    - name: var1
      type: String
      description: ""
      value: <+input>
